### ISSUE TITLE
Blockquote Plugin breaks dokuwiki

### ISSUE THREAD

**Issue by chainsawbeaver** [dokufreaks/plugin-blockquote#22]
Before the update to "Hogfather" I had the Blockquote Plug-in running. Also before updating I noticed that the Plug-in was not compatible with 2020-07-29 "Hogfather" so I deactivated it (and used a self defined WRAP-Block instead).

Now I noticed that the status switched to "Compatible with DokuWiki 2020-07-29 "Hogfather"  yes", so I activated it in the admin pages. After that the webpage breaks and I get these messages in the apache log file:

```
[Wed Sep 02 11:47:40.960132 2020] [:error] [pid 18085] [client redacted:53136] PHP Fatal error:  Declaration of syntax_plugin_blockquote_quote::handle($match, $state, $pos, &$handler) must be compatible with dokuwiki\\Extension\\SyntaxPlugin::handle($match, $state, $pos, Doku_Handler $handler) in /var/www/html/wiki/lib/plugins/blockquote/syntax/quote.php on line 0
```

So far I only tried a reinstall of the Plug-in, which did not help.

**Comment by Klap-in** [comment]
The file mentioned in this error message does not exist anymore in the current version of the plugin. 
Did you update it before the upgrade? If I understand it correctly, I guess not. 

Probably the easiest is to delete the folder of the plugin, and reinstall it later.

The current code looks like that this issue is fixed sometime ago.

**Comment by Klap-in** [comment]
I see the issue:
`quote.php` is an old file. Which is deleted in the past. But DokuWiki does not delete files of plugins, without explicit request of the plugin author. To fix this issue, I have added `deleted.files` which does this request.

So if you retry to update your plugin, I expect that the issue is solved by the automatic deletion of the old file (which contains deprecated code)

**Comment by chainsawbeaver** [comment]
Thank you Klap-in, now it works
